import SearchBar from "./components/search-bar/searchBar";
import "./globals.css";
import { Inter } from "next/font/google";
import { GlobalContextProvider } from "./context/store";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "MELI Challenge",
  description: "Generated by Alexis Pucheta",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className="bg-white">
        <GlobalContextProvider>
          <SearchBar></SearchBar>
          <div className="grid grid-cols-12 gap-4 px-4 bg-[#EEEEEE] min-h-screen pb-[46px]">
            <div className="col-start-2 col-span-10">{children}</div>
          </div>
        </GlobalContextProvider>
      </body>
    </html>
  );
}
